### ISSUE TITLE
`*.txt` to `*.md`

### ISSUE THREAD

**Issue by sensasi-delight** [AlyaKagerou/Alyanation-goals#5]
Bang, kenapa gak dibuat jadi file markdown untuk plans dan goals-nya❓

**Comment by AlyaKagerou** [comment]
hmmmm.... gimana ini sih sebenarnya contoh aja... soalnya aku masih belajar git ama github hehe

**Comment by AlyaKagerou** [comment]
mungkin kedepannya bisa aku ubahin .md nya

**Comment by sensasi-delight** [comment]
coba aku pull request ya bang, biar abang bisa liat contohnya

**Comment by sensasi-delight** [comment]
lah udah jadi `*.md`.

coba aku sempurnakan ya bang xixixi

**Comment by AlyaKagerou** [comment]
Booooleeeeehhhhh hehe

**Comment by sensasi-delight** [comment]
> Booooleeeeehhhhh hehe

cek PR #6
